### ISSUE TITLE
Naming the game

### ISSUE THREAD

**Issue by heckert-gamedev** [abycoder500/holisticjamgame#16]
Do we have some name for the game already?
I would think something like "Codename: 'Project Johnnyboy'" would match nicely.

if we want to go somewhat dark, sinister, and dystopian, we could have some evil entity called "World Intellectual Property" (which incidentally is abbreviated as "W.I.P." , which matches with "work in progress")...

If we take the game to be a "Simulated Interactive Environment", we could shorten the whole name to be "Wipsie"...

**Comment by l0lvers** [comment]
We could go with john the labrat 
Edit: after reading yours it looks better
Edit 2: i meant the codename one

**Comment by heckert-gamedev** [comment]
Contributes to #23

**Comment by heckert-gamedev** [comment]
Ok, I'll go with 
### **Codename: "Project Johnnybox"**
and open a page on itch.io for it.
