### ISSUE TITLE
Finishing touches, a.k.a. credits roll

### ISSUE THREAD

**Issue by heckert-gamedev** [abycoder500/holisticjamgame#17]
The credits screen could totally have some background music that starts with "Queen: We want to break free", but we shouldn't have more than just the first couple of notes of it (just the first 5 chords/notes of the song should be sufficient)...

**Comment by l0lvers** [comment]
I had the idea of getting some peaceful music from sarmen

**Comment by heckert-gamedev** [comment]
Would it rule out starting with the intro riffs to that Queen song?

**Comment by heckert-gamedev** [comment]
Well, no real "end" screen, and not really much of audio except for the intro voice... but the jam is done
