### ISSUE TITLE
Prepare page on itch.io

### ISSUE THREAD

**Issue by heckert-gamedev** [abycoder500/holisticjamgame#23]
Have we decided on the name, yet?
Who will be the primary contributor under whose account the game will reside?
Since the repo and everything is under @abycoder500 's account, that would be the place?
Otherwise I would well be willing to setup a page and handle the releasing tasks.

**Comment by heckert-gamedev** [comment]
Naming see #16

**Comment by abycoder500** [comment]
you can go ahead and setup an itch page!

**Comment by heckert-gamedev** [comment]
Ok, will do!

**Comment by heckert-gamedev** [comment]
> You open your eyes, but the surrounding world is pitch black. After a moment you manage to make out some faint shades of a room.
> Now, where are you? What happened? And what's that voice that suddenly started talking? And why is it calling you "Johhnyboy"?
> Enter the game to find out!
