### ISSUE TITLE
FPS Controller

### ISSUE THREAD

**Issue by daryoush12** [abycoder500/holisticjamgame#5]
FPS Controller should include atleast following:

- WASD Movement
- E to interact with Objects in world. 
- Interaction interface

**Comment by heckert-gamedev** [comment]
By default the asset's playercontroller has WASD movement, but sideways is strafe, for turning you need to look around using the mouse.
I would rather have it turn around and have some other strafing key (or using a key as modifier to switch between turning and strafing), but the question would be: Do we need/want strafing?

**Comment by heckert-gamedev** [comment]
I would think if WASD is movement like it is, there could be `Q` and `E` for turning and we could have `R` ("reach") to interact with objects. One could even go one further and have `t` for "talk". But we should keep it as simple as possible for the moment and not add too many more things to it.
Additionally there is already "Left Shift" (and Left Trigger on a gamepad) defined as "Sprint".

**Comment by heckert-gamedev** [comment]
I opened #21 to continue on the turning by keyboard feature.
What ecactly did you mean with "interaction interface"?
I think the controller as it is has what we need and will close the issue. If you think otherwise, please re-open or start a follow-up issue detailing what's missing and needed.
