### ISSUE TITLE
Interaction with objects

### ISSUE THREAD

**Issue by heckert-gamedev** [abycoder500/holisticjamgame#7]
So, interactible objects will tell the broker if they get "tickled" by the player's presence. 
This can be used to send an **event** to the UI which could show a hint like "press key to interact" to tell the player there's something to interact with nearby.
When the player presses the button, this will be sent as an "Interaction request" event to the broker. 
The broker will know if there's something to interact with and trigger an "**interact**" event to whatever object has shown interest.
The interactible object could just subscribe to that event if it is ready to be interacted with, but even if it's currently not receptive (say, a door is still locked) it might send some info to the broker so the UI will get the message and turn it off again if the player leaves the interaction zone...

We could have different type of interactions: one-press activation, on/off switch, some button that needs to be pressed over some amount of time. but first just simple button press. on/off might also be pick-up/drop...

![Interaction-Events2022-07-08-2258](https://user-images.githubusercontent.com/86689295/178073739-e29db540-7784-4afc-b2e7-2f3ca67e6119.png)

**Comment by daryoush12** [comment]
I do not see anything that requires immediate reaction and such it can be implemented at your earliest convienence.

**Comment by heckert-gamedev** [comment]
Next step will be setting up that an object can show a message on the UI when the player enters its trigger area (instead of having debug log messages). This should be in a way that there can be no message as well (for hidden buttons). Also, the dummy action performed needs to be able to be overridden, so interactible objects in the game can do various things. Either by having a script that inherits from `InteractibleObject` or by having some component and/or child object for this.
Also, it should be possible to point an `InteractibleObject` to a target object, so we can have a button at some place that triggers a door at another position more easily.

**Comment by heckert-gamedev** [comment]
The framework for having an interaction target another object as well as being able to easily implement more interaction responses is implemented with #18
When the PR is merged, this issue could be closed.
